

-- 1.Find products sold in the highest quantity.

SELECT 
    p.product_name,
    SUM(o.quantity) products_with_highest_quantity
FROM 
    challenge_50_project.clean_products p

JOIN challenge_50_project.clean_order_details o
ON o.product_id = p.product_id
GROUP BY p.product_name
ORDER BY 2 DESC
LIMIT 1;

--2.Find the least selling products.

SELECT 
    p.product_name,
    SUM(o.quantity) least_selling_product
FROM 
    challenge_50_project.clean_products p

JOIN challenge_50_project.clean_order_details o
ON o.product_id = p.product_id
GROUP BY p.product_name
ORDER BY 2
LIMIT 1;

--3.Find revenue generated by each product.

SELECT 
    p.product_name,
    SUM((o.quantity*P.price)) AS total_revenue   
FROM 
    challenge_50_project.clean_products p

JOIN challenge_50_project.clean_order_details o
ON o.product_id = p.product_id
GROUP BY p.product_name
ORDER BY 2 DESC;


-- 4.Find total sales for each category.

SELECT 
    p.category,
    SUM((o.quantity*P.price)) AS total_revenue   
FROM 
    challenge_50_project.clean_products p

JOIN challenge_50_project.clean_order_details o
ON o.product_id = p.product_id
GROUP BY p.category
ORDER BY 2 DESC;


-- 5.Find the highest priced product that was sold.


SELECT product_name
FROM challenge_50_project.clean_products

WHERE price = 
(
    SELECT 
        MAX(price)
    FROM 
        challenge_50_project.clean_products
);


-- 6.Find average product price category-wise.

SELECT
    product_name,
    category,
    AVG(price)OVER(PARTITION BY category) AS avg_price_category_wise
FROM challenge_50_project.clean_products



-- 7.Find daily quantity sold for each product.

SELECT 
    p.product_name,
    co.order_date,
   ROUND(AVG(o.quantity)) AS avg_quanity_of_products
FROM 
    challenge_50_project.clean_products p

JOIN challenge_50_project.clean_order_details o
ON o.product_id = p.product_id
JOIN challenge_50_project.clean_orders co
ON o.order_id = co.order_id
GROUP BY p.product_name,co.order_date
ORDER BY 3 DESC;